import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "TodoList With Next.js and Googlesheets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster/>
        <header className="bg-indigo-50 p-6 mb-8 border border-slate-400">
          <h1 className="text-center font-bold text-xl">- Todo List With Next.js and Googlesheets -</h1>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
