import "./globals.css";

export const metadata = {
  title: "Practice with googlesheets",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-pink-100 p-5 mb-8">
          <h1 className="text-center font-bold">- Todo List Using Next.js and Googlesheets -</h1>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
